### ISSUE TITLE
Still getting an error with Emberfire

### ISSUE THREAD

**Issue by davidlormor** [gabrielgrant/ember-cli-test-model-waiter#4]
Installed this addon hoping to resolve async testing issues with EmberFire, but I'm still getting errors. Not really sure where to even start to debug, so any help would be greatly appreciated :smile:

Version info:

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.3.0
DEBUG:` Ember Data : 2.3.3
DEBUG: Firebase   : 2.4.0
DEBUG: EmberFire  : 1.6.4
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

Testem output:

```
Global error: Error: Adapter operation failed at http://localhost:7357/assets/vendor.js, line 65640

Unit | Model | tour: currentStop can be incremented
✘ Promise rejected after currentStop can be incremented: Assertion Failed: You can only unload a record which is not inFlight. `<tour:null>`
Error: Assertion Failed: You can only unload a record which is not inFlight. `<tour:null>`
✘ Error: Adapter operation failed http://localhost:7357/assets/vendor.js:65640
Error: Adapter operation failed at http://localhost:7357/assets/vendor.js, line 65640
```

Code in question:

``` javascript
// models/tour.js
export default DS.Model.extend({
  currentStop: DS.attr('number', {defaultValue: 1}),

  incrementCurrentStop: function() {
    this.incrementProperty('currentStop');
    this.save();
  }
});

// tour-test.js
test('currentStop can be incremented', function(assert) {
  const tour = this.subject({
    currentStop: 1
  });
  Ember.run(function() {
    tour.incrementCurrentStop();
  });
  assert.equal(tour.get('currentStop'), 2, 'currentStop was incremented by 1');
});
```

**Comment by gabrielgrant** [comment]
Hey, sorry for taking so long to get back to this.

This addon is primarily designed for use with acceptance tests, where assertions would be wrapped in an `andThen()` to ensure they've waited for all async behavior to complete.

I'd generally recommend against saving a record within a method on your model and instead call `model.save()` explicitly from the containing code. In that case, a unit test like this would just inspect the model state without waiting for the network round-trip. If you do really need to save within the model method, you'll need to figure out some way to get the test to wait for async behavior. You could try using `andThen()` but I'm honestly not sure how/whether that would work (would likely also need to be in the run loop). If you've figured it out, let me know what ended up working!

I'm going to close this for now, since it isn't really a supported use case, but if you can share a compelling reason for saving a model in your unit test, I'd consider re-opening this as a feature request.
